### ISSUE TITLE
你才整天缺乏品位踩缝纫机，你不是中国人，你无权评价我们

### ISSUE THREAD

**Issue by gittestkey** [Meritamen/.emacs.d#3]
https://github.com/cirosantilli/china-dictatorship/issues/1119
你才整天缺乏品位踩缝纫机，你不是中国人，你无权评价我们，脆弱的是你们，整天在那看着我们强大了就来逼逼赖赖。自己看看日本二战后的芯片崛起，一下子被自己的父亲（美国）给打下去了，整天在那里打各种国家（伊拉克……），你自己去打吧。
最好一辈子也别用中国造的产品，好好看看你电脑上的零件。

最后，想想Github是干什么用的。

**Comment by Meritamen** [comment]
Ching chang chong
